# Generated by Django 6.0.2 on 2026-03-12 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('active_goal_title', models.CharField(blank=True, default='Set a Goal', max_length=255)),
                ('active_goal_books_completed', models.IntegerField(default=0)),
                ('active_goal_total_books', models.IntegerField(default=1)),
                ('total_books_read', models.IntegerField(default=0)),
                ('total_hours_read', models.IntegerField(default=0)),
                ('total_quotes_saved', models.IntegerField(default=0)),
                ('mood_before_reading', models.FloatField(default=0.0)),
                ('mood_after_reading', models.FloatField(default=0.0)),
                ('weekly_digest_text', models.TextField(blank=True, default='')),
                ('weekly_digest_date_range', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
