# Generated by Django 6.0.2 on 2026-03-12 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('reflections_written', models.IntegerField(default=0)),
                ('challenges_done', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_improvement_percentage', models.IntegerField(default=0)),
                ('daily_average_minutes', models.IntegerField(default=0)),
                ('longest_session_minutes', models.IntegerField(default=0)),
                ('mon_progress', models.FloatField(default=0.0)),
                ('tue_progress', models.FloatField(default=0.0)),
                ('wed_progress', models.FloatField(default=0.0)),
                ('thu_progress', models.FloatField(default=0.0)),
                ('fri_progress', models.FloatField(default=0.0)),
                ('sat_progress', models.FloatField(default=0.0)),
                ('sun_progress', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('book', models.CharField(max_length=255)),
                ('date_saved', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
