# Generated by Django 6.0.2 on 2026-03-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_goaldetails_readinganalytics_savedquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='mood_after_reading',
            field=models.CharField(default='3.2,3.5,2.8,4.0,4.2,3.8', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='mood_before_reading',
            field=models.CharField(default='2.5,2.5,2.0,2.8,3.2,3.2', max_length=255),
        ),
    ]
