# Generated by Django 6.0.2 on 2026-03-12 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprogress_mood_after_reading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('insight_title', models.CharField(default='Find Your Inner Calm', max_length=255)),
                ('quote_text', models.TextField()),
                ('quote_author', models.CharField(max_length=255)),
                ('article_title', models.CharField(max_length=255)),
                ('article_preview', models.TextField()),
                ('ai_reflection', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_earned', models.DateField(auto_now_add=True)),
                ('icon_name', models.CharField(max_length=100)),
                ('tint_color', models.CharField(max_length=50)),
                ('bg_color', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
