# Generated by Django 6.0.2 on 2026-03-14 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_dailyboost_journalentry_userbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[('TOP', 'Top Books'), ('MONTH', 'Books of the Month'), ('TRENDING', 'Trending in Motivation'), ('RECOMMENDED', 'AI Recommendation')], default='TRENDING', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_editorial', models.BooleanField(default=False)),
                ('article_title', models.CharField(blank=True, max_length=255, null=True)),
                ('article_preview', models.TextField(blank=True, null=True)),
                ('read_time_minutes', models.IntegerField(default=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
