# Generated by Django 6.0.2 on 2026-03-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_book_feedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='current_book_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_book_is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_book_progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_book_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
