# Generated by Django 6.0.2 on 2026-03-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_readinganalytics_pages_read_readingpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='total_highlights_made',
            field=models.IntegerField(default=0),
        ),
    ]
