# Generated by Django 6.0.2 on 2026-03-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprogress_total_highlights_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='active_goal_subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
