# Generated by Django 6.0.2 on 2026-03-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_challenge_userprogress_active_goal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingpreference',
            name='improvement_goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='readingpreference',
            name='interests',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='readingpreference',
            name='reading_style',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
