# Generated by Django 6.0.2 on 2026-03-17 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_readingpreference_improvement_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyboost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_boosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyboost',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='dailyboost',
            unique_together={('user', 'date')},
        ),
    ]
