# Generated by Django 6.0.2 on 2026-03-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_dailyboost_user_alter_dailyboost_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('rough', 'Rough'), ('okay', 'Okay'), ('great', 'Great')], default='okay', max_length=10),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(blank=True, default='Daily Reflection', max_length=255),
        ),
    ]
