# Generated by Django 6.0.2 on 2026-03-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
