# Generated by Django 6.0.2 on 2026-03-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
