# Generated by Django 6.0.2 on 2026-03-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_devicetoken_notificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='total_notes_taken',
            field=models.IntegerField(default=0),
        ),
    ]
